Release/2.0
rokket-labs/aws-serverless-template pull request #1
Opened 2021-10-06 15:01 UTC by Yhozen

## Done
- Update mongoose to v6
- Remove @fiquu packages
- Add typegoose 
- Add husky
- Fix github actions `deploy` and `test`(thanks @czhoffmann23)
- Remove `package-lock.json`

## TO-DO / Optional:
Switch GraphQL strategy to code-first

2021-10-06 20:02 UTC, tomcastro requested changes

2021-10-06 20:02 UTC, tomcastro commented on package.json
> +    "@types/jest": "^27.0.2",
Could you update ESLint and Prettier dependencies as well?

2021-10-06 20:28 UTC, Yhozen commented on package.json
> +    "@types/jest": "^27.0.2",
ready

2021-10-07 13:17 UTC, tomcastro approved these changes

2021-10-07 13:17 UTC, merged